### ISSUE TITLE
SAS Token para lectura

### ISSUE THREAD

**Issue by icebeam7** [lruval/XamarinChampionship#3]
¿Sería posible proporcionar un token de solo lectura que nos permitiera corroborar que los blobs fueron creados correctamente? El token del Reto 7 solo permite operaciones de escritura, por lo que sería necesario otro. ¡Gracias!

**Comment by luisingsis27** [comment]
ya pudis corroborar si el blob fue creado correctamente @icebeam7

**Comment by icebeam7** [comment]
¿Es pregunta? Si es el caso, no, no es posible aún corroborar si el blob ha sido creado correctamente porque el SAS token proporcionado en el reto es de solo escritura. En teoría si fue creado satisfactoriamente porque no obtuve una excepción al momento de resolver el reto, solo que digamos que quería "estar seguro".

**Comment by luisingsis27** [comment]
yo tampoco tuve excepción, pero me gustaría estar seguro de que blob se haya creado correctamente. @lruval podrías proporcionar un token de lectura para verificar que el blob se haya creado correctamente.
@icebeam7

**Comment by luisruval** [comment]
Hola, el token SAS para sólo lectura es el siguiente: 

?sv=2016-05-31&ss=b&srt=sco&sp=rla&se=2017-12-31T23:59:59Z&st=2017-05-22T01:00:00Z&sip=0.0.0.0-255.255.255.255&spr=https,http&sig=AqV8IIX7Nu9ai3lQhlJ1GqtNNLVo%2BKbkDoW4qxeIUpA%3D

Saludos,

-Luis

**Comment by icebeam7** [comment]
¡Muchas gracias! Funciona a la perfección y ya vi que mis dos archivos (imagen y archivo de texto) puderon ser descargados sin problemas.

Estuvo interesante el reto :)
