### ISSUE TITLE
Facebook App esta en development

### ISSUE THREAD

**Issue by AlejandroRuiz** [lruval/XamarinChampionship#4]
Parece que la app Facebook sigue en development y no permite login de usuarios no añadidos como desarrolador/testers  etc. esto impide terminar el reto 8
<img width="441" alt="screen shot 2017-06-05 at 6 34 19 pm" src="https://cloud.githubusercontent.com/assets/1253565/26807731/d318dfb6-4a1d-11e7-964f-ea2116da66b9.png">

**Comment by icebeam7** [comment]
Confirmo, me apareció el mismo mensaje.

![error_fb](https://cloud.githubusercontent.com/assets/6038239/26808019/b9af6548-4a1f-11e7-8f58-c6238fe9cca9.png)

**Comment by icebeam7** [comment]
Arreglado, ya me dejó!

**Comment by AlejandroRuiz** [comment]
Cierto ya funciono
